[package]
name = "musilk-rust-piccolo"
version = "0.1.0"
edition = "2024"

[dependencies]
runtime = {path = "runtime"}
editor = {path = "editor"}
log = "0.4.28"
serde = "1.0.228"
rand = "0.9.2"
typetag = "0.2.21"
