[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
imgui = {version = "0.12.0", features = ["docking"]}
log = "0.4.28"
runtime = {path = "../runtime"}
winit = "0.30.12"
